# Generated by Django 5.2.8 on 2025-11-28 03:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token_verificacion', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Verificación'), ('ACTIVO', 'Verificado y Participando'), ('GANADOR', 'Ganador del Sorteo')], default='PENDIENTE', max_length=20)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
