# Generated by Django 5.2.8 on 2025-11-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
    ]
